config/routes.rb
Store::Application.routes.draw do

  devise_for :users

  resources :users
  resources :products do
    resources :reviews, only: [:create]
  end

  root :to => 'products#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :photo

  belongs_to :attachable, polymorphic: true

  has_attached_file :photo, styles: { medium: "300x300", thumb: "100x100" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :content, :name, :price, :user_id, :attachments_attributes
  PER_PAGE_NUMBER = 10

  has_many :attachments, as: :attachable

  accepts_nested_attributes_for :attachments, allow_destroy: :true
  belongs_to :user
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment

  belongs_to :product
  belongs_to :user

  def display_user_email
    user.email
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.order("id").page(params[:page]).per(Product::PER_PAGE_NUMBER)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @review = Review.new
    @reviews = @product.reviews
    @attachments = @product.attachments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @attachment = @product.attachments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product

  def create
    @review = @product.reviews.new(params[:review])
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: "Thank you for reviewing this product"}
        format.js
      else
        format.html { render action: :new }
        format.js
      end
    end
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def allowed?(id)
    current_user.id == id
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> |
    <%= link_to 'Edit profile', edit_user_registration_path %>
  </li>
<% else %>
  <li>
    <%= link_to 'Sign In', new_user_session_path %> |
    <%= link_to 'Sign Up', new_user_registration_path %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">
	 <div class="row">
		<%= yield %>
   </div>
 </div>
</body>
</html>

app/views/products/_form.html.erb
<%= nested_form_for @product, html: { class: :'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, class: :'control-label' %>
    <div class="controls">
      <%= f.text_field :name, class: :'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, class: :'control-label' %>
    <div class="controls">
      <%= f.text_area :content, class: :'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, class: :'control-label' %>
    <div class="controls">
      <%= f.number_field :price, class: :'number_field' %>
    </div>
  </div>
  <div class="form-actions">
    <p>
      <%= f.link_to_add "Add new attachment", :attachments %>
    </p>
    <%= f.fields_for :attachments do |attachment| %>
      <%= attachment.file_field :photo %>
      <%= attachment.link_to_remove "Remove this attachment" %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-default btn-lg pull-left' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default btn-lg pull-left' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: :model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: :'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
        <img src="https://pbs.twimg.com/profile_images/2308365558/CD_favicon_large_bigger.gif" alt="Responsive image" class="img-circle pull-left min-image-height">
      <a class="brand"> Kitchen Krafts</a>
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Browse Products", products_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="page-header">

  <h1><%=t '.title', default: :model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to "New Product", new_product_path, class: 'btn btn-default btn-lg pull-right' %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= product.content %></td>
        <td><%= product.price %></td>
        <td><%= product.user.email %></td>
        <td>
          <% if allowed?(product.user.id) %>
        <td><%= link_to t('.edit', default: :t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-default btn-lg' %></td>
        <td><%= link_to t('.destroy', default: :t("helpers.links.destroy")), product_path(product), method: :delete,data: { confirm: :t('.confirm', :default => t("helpers.links.confirm", default: :'Are you sure?')) }, class: :'btn btn-default btn-lg' %></td>
        </td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>

  <p class="text-justify">
    <div class="span9">
      <h2>About Us</h2>
        <em>
            Kitchen Krafts, Inc. is a direct merchant of hard-to-find cooking tools, ingredients & supplies for creative cooks. Our product range encompasses the categories: cake decorating, home baking, candy making and home canning supplies. Within each category we offer a full range of tools, supplies, ingredients, books, how-to videos and packaging products.
       </em>
    </div>
  </p>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], model: :model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', default: :model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @product.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @product.user.email%></dd>
</dl>

<% @attachments.each do |attachment| %>
 <%= image_tag attachment.photo.url(:medium) %>
<% end %>

<h2>Review:</h2>
<div class="product-review">
  <%= render @reviews %>
</div>

<h2>Add a review:</h2>
<%= render "reviews/form" %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review], remote: :true) do |f| %>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/_review.html.erb
<div class="add_review">
	<strong>Name:</strong>
	<%= review.user.email %>
</div>

<div>
	<strong>Review:</strong>
	<%= review.comment %>
</div>

app/views/reviews/create.js.erb
$('.product-review').append("<%= escape_javascript (render partial: 'review', locals: { review: @review }) %>");
$('#review_comment').val('');

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.comment %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>